version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6381:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env  
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}   # Update DATABASE_URL with service name 'db'
      - REDIS_URL=redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
    depends_on:
      - db
      - redis

volumes:
  db_data:
